[build]
  command = "cd frontend && npm ci && npm run build"
  publish = "frontend/dist"

[functions]
  directory = "backend/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200