[build]
  # Use root workspace install so both functions and frontend deps are installed
  command = "npm install && npm --workspace frontend run build"
  publish = "frontend/dist"

[functions]
  directory = "backend/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200